//============================================
//                    User
//============================================
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'

export const CONFIRM_USER_REQUEST = 'CONFIRM_USER_REQUEST'
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS'
export const CONFIRM_USER_FAILURE = 'CONFIRM_USER_FAILURE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const LOAD_CART_ITEMS_REQUEST = 'LOAD_CART_ITEMS_REQUEST';
export const LOAD_CART_ITEMS_SUCCESS = 'LOAD_CART_ITEMS_SUCCESS';
export const LOAD_CART_ITEMS_FAILURE = 'LOAD_CART_ITEMS_FAILURE';

export const REMOVE_CART_ITEM_REQUEST = 'REMOVE_CART_ITEM_REQUEST';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAILURE = 'REMOVE_CART_ITEM_FAILURE';

//============================================
//                   Movie
//============================================
export const LOAD_MOVIES_REQUEST = 'LOAD_MOVIES_REQUEST'
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE'

export const LOAD_MOVIE_DETAIL_REQUEST = 'LOAD_MOVIE_DETAIL_REQUEST';
export const LOAD_MOVIE_DETAIL_SUCCESS = 'LOAD_MOVIE_DETAIL_SUCCESS';
export const LOAD_MOVIE_DETAIL_FAILURE = 'LOAD_MOVIE_DETAIL_FAILURE';

export const LOAD_MOVIE_TRAILER_REQUEST = 'LOAD_MOVIE_TRAILER_REQUEST';
export const LOAD_MOVIE_TRAILER_SUCCESS = 'LOAD_MOVIE_TRAILER_SUCCESS';
export const LOAD_MOVIE_TRAILER_FAILURE = 'LOAD_MOVIE_TRAILER_FAILURE';

export const LOAD_MOVIE_CASTING_REQUEST = 'LOAD_MOVIE_CASTING_REQUEST';
export const LOAD_MOVIE_CASTING_SUCCESS = 'LOAD_MOVIE_CASTING_SUCCESS';
export const LOAD_MOVIE_CASTING_FAILURE = 'LOAD_MOVIE_CASTING_FAILURE';


//=========================================
//                 Movie - Favorite
//=========================================
export const LOAD_FAVORITE_NUMBER_REQUEST = 'LOAD_FAVORITE_NUMBER_REQUEST';
export const LOAD_FAVORITE_NUMBER_SUCCESS = 'LOAD_FAVORITE_NUMBER_SUCCESS';
export const LOAD_FAVORITE_NUMBER_FAILURE = 'LOAD_FAVORITE_NUMBER_FAILURE';

export const CHANGE_FAVORITE_REQUEST = 'CHANGE_FAVORITE_REQUEST';
export const CHANGE_FAVORITE_SUCCESS = 'CHANGE_FAVORITE_SUCCESS';
export const CHANGE_FAVORITE_FAILURE = 'CHANGE_FAVORITE_FAILURE';

export const LOAD_IS_FAVORITED_REQUEST = 'LOAD_IS_FAVORITED_REQUEST';
export const LOAD_IS_FAVORITED_SUCCESS = 'LOAD_IS_FAVORITED_SUCCESS';
export const LOAD_IS_FAVORITED_FAILURE = 'LOAD_IS_FAVORITED_FAILURE';

export const LOAD_FAVORITED_LIST_REQUEST = 'LOAD_FAVORITED_LIST_REQUEST';
export const LOAD_FAVORITED_LIST_SUCCESS = 'LOAD_FAVORITED_LIST_SUCCESS';
export const LOAD_FAVORITED_LIST_FAILURE = 'LOAD_FAVORITED_LIST_FAILURE';


//=========================================
//                 Jaymall
//=========================================
export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAILURE = 'LOAD_PRODUCTS_FAILURE';

export const UPLOAD_PRODUCT_REQUEST = 'UPLOAD_PRODUCT_REQUEST';
export const UPLOAD_PRODUCT_SUCCESS = 'UPLOAD_PRODUCT_SUCCESS';
export const UPLOAD_PRODUCT_FAILURE = 'UPLOAD_PRODUCT_FAILURE';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const REMOVE_UPLOADED_IMAGE = 'REMOVE_UPLOADED_IMAGE';

export const RESET_UPLOAD_IMAGE = 'RESET_UPLOAD_IMAGE';

export const LOAD_PRODUCT_DETAILS_REQUEST = 'LOAD_PRODUCT_DETAILS_REQUEST';
export const LOAD_PRODUCT_DETAILS_SUCCESS = 'LOAD_PRODUCT_DETAILS_SUCCESS';
export const LOAD_PRODUCT_DETAILS_FAILURE = 'LOAD_PRODUCT_DETAILS_FAILURE';

export const SET_ALL_FILTERS_INFO = 'SET_ALL_FILTERS_INFO';
export const RESET_PRODUCTS = 'RESET_PRODUCTS';


//=========================================
//                 Blog
//=========================================
export const CREATE_BLOG_POST_REQUEST = 'CREATE_BLOG_POST_REQUEST';
export const CREATE_BLOG_POST_SUCCESS = 'CREATE_BLOG_POST_SUCCESS';
export const CREATE_BLOG_POST_FAILURE = 'CREATE_BLOG_POST_FAILURE';

export const RESET_CREATE_BLOG_POST = 'RESET_CREATE_BLOG_POST';

export const LOAD_BLOG_POSTS_REQUEST = 'LOAD_BLOG_POSTS_REQUEST';
export const LOAD_BLOG_POSTS_SUCCESS = 'LOAD_BLOG_POSTS_SUCCESS';
export const LOAD_BLOG_POSTS_FAILURE = 'LOAD_BLOG_POSTS_FAILURE';

export const RESET_LOAD_BLOG_POSTS = 'RESET_LOAD_BLOG_POSTS';

export const LOAD_BLOG_POST_REQUEST = 'LOAD_BLOG_POST_REQUEST';
export const LOAD_BLOG_POST_SUCCESS = 'LOAD_BLOG_POST_SUCCESS';
export const LOAD_BLOG_POST_FAILURE = 'LOAD_BLOG_POST_FAILURE';


//=========================================
//                 Chat
//=========================================
export const REGISTER_CHAT_USER_REQUEST = 'REGISTER_CHAT_USER_REQUEST'
export const REGISTER_CHAT_USER_SUCCESS = 'REGISTER_CHAT_USER_SUCCESS'
export const REGISTER_CHAT_USER_FAILURE = 'REGISTER_CHAT_USER_FAILURE'

export const LOGIN_CHAT_USER_REQUEST = 'LOGIN_CHAT_USER_REQUEST'
export const LOGIN_CHAT_USER_SUCCESS = 'LOGIN_CHAT_USER_SUCCESS'
export const LOGIN_CHAT_USER_FAILURE = 'LOGIN_CHAT_USER_FAILURE'

export const LOGOUT_CHAT_USER_REQUEST = 'LOGOUT_CHAT_USER_REQUEST'
export const LOGOUT_CHAT_USER_SUCCESS = 'LOGOUT_CHAT_USER_SUCCESS'
export const LOGOUT_CHAT_USER_FAILURE = 'LOGOUT_CHAT_USER_FAILURE'

export const SET_CHAT_USER = 'SET_CHAT_USER';

export const SET_CURRENT_CHAT_ROOM = 'SET_CURRENT_CHAT_ROOM';
